### ISSUE TITLE
Incompatible with libmupdf 1.12.0-2

### ISSUE THREAD

**Issue by qikiqi** [jichu4n/JFBView#17]
make results to the following, trying to compile with libmupdf 1.12.0-2

```
make
g++ -Wall -O2 -std=c++1y -DMUPDF_VERSION=10012   -c -o pdf_document.o pdf_document.cpp
pdf_document.cpp: In member function ‘virtual void PDFDocument::Render(Document::PixelWriter*, int, float, int)’:
pdf_document.cpp:162:56: error: invalid conversion from ‘int’ to ‘fz_separations* {aka fz_separations_s*}’ [-fpermissive]
       _fz_context, fz_device_rgb(_fz_context), &bbox, 1);
                                                        ^
pdf_document.cpp:162:56: error: too few arguments to function ‘fz_pixmap* fz_new_pixmap_with_bbox(fz_context*, fz_colorspace*, const fz_irect*, fz_separations*, int)’
In file included from /usr/include/mupdf/fitz.h:35:0,
                 from /usr/include/mupdf/pdf.h:4,
                 from pdf_document.cpp:29:
/usr/include/mupdf/fitz/pixmap.h:86:12: note: declared here
 fz_pixmap *fz_new_pixmap_with_bbox(fz_context *ctx, fz_colorspace *colorspace, const fz_irect *bbox, fz_separations *seps, int alpha);
            ^~~~~~~~~~~~~~~~~~~~~~~
pdf_document.cpp: In member function ‘std::__cxx11::string PDFDocument::GetPageText(int, int)’:
pdf_document.cpp:231:3: error: ‘fz_stext_sheet’ was not declared in this scope
   fz_stext_sheet* text_sheet = fz_new_stext_sheet(_fz_context);
   ^~~~~~~~~~~~~~
pdf_document.cpp:231:3: note: suggested alternative: ‘fz_stext_page’
   fz_stext_sheet* text_sheet = fz_new_stext_sheet(_fz_context);
   ^~~~~~~~~~~~~~
   fz_stext_page
pdf_document.cpp:231:19: error: ‘text_sheet’ was not declared in this scope
   fz_stext_sheet* text_sheet = fz_new_stext_sheet(_fz_context);
                   ^~~~~~~~~~
pdf_document.cpp:231:32: error: ‘fz_new_stext_sheet’ was not declared in this scope
   fz_stext_sheet* text_sheet = fz_new_stext_sheet(_fz_context);
                                ^~~~~~~~~~~~~~~~~~
pdf_document.cpp:231:32: note: suggested alternative: ‘fz_new_stext_page’
   fz_stext_sheet* text_sheet = fz_new_stext_sheet(_fz_context);
                                ^~~~~~~~~~~~~~~~~~
                                fz_new_stext_page
pdf_document.cpp:258:8: error: ‘fz_page_block’ was not declared in this scope
   for (fz_page_block* page_block = text_page->blocks;
        ^~~~~~~~~~~~~
pdf_document.cpp:258:8: note: suggested alternative: ‘fz_page_s’
   for (fz_page_block* page_block = text_page->blocks;
        ^~~~~~~~~~~~~
        fz_page_s
pdf_document.cpp:258:23: error: ‘page_block’ was not declared in this scope
   for (fz_page_block* page_block = text_page->blocks;
                       ^~~~~~~~~~
pdf_document.cpp:258:23: note: suggested alternative: ‘page_struct’
   for (fz_page_block* page_block = text_page->blocks;
                       ^~~~~~~~~~
                       page_struct
pdf_document.cpp:258:47: error: ‘fz_stext_page {aka struct fz_stext_page_s}’ has no member named ‘blocks’
   for (fz_page_block* page_block = text_page->blocks;
                                               ^~~~~~
pdf_document.cpp:259:32: error: ‘fz_stext_page {aka struct fz_stext_page_s}’ has no member named ‘blocks’
        page_block < text_page->blocks + text_page->len;
                                ^~~~~~
pdf_document.cpp:259:52: error: ‘fz_stext_page {aka struct fz_stext_page_s}’ has no member named ‘len’
        page_block < text_page->blocks + text_page->len;
                                                    ^~~
pdf_document.cpp:262:29: error: ‘FZ_PAGE_BLOCK_TEXT’ was not declared in this scope
     if (page_block->type != FZ_PAGE_BLOCK_TEXT) {
                             ^~~~~~~~~~~~~~~~~~
pdf_document.cpp:262:29: note: suggested alternative: ‘FZ_STEXT_BLOCK_TEXT’
     if (page_block->type != FZ_PAGE_BLOCK_TEXT) {
                             ^~~~~~~~~~~~~~~~~~
                             FZ_STEXT_BLOCK_TEXT
pdf_document.cpp:267:49: error: ‘fz_stext_block {aka struct fz_stext_block_s}’ has no member named ‘lines’
     for (fz_stext_line* text_line = text_block->lines;
                                                 ^~~~~
pdf_document.cpp:268:34: error: ‘fz_stext_block {aka struct fz_stext_block_s}’ has no member named ‘lines’
          text_line < text_block->lines + text_block->len;
                                  ^~~~~
pdf_document.cpp:268:54: error: ‘fz_stext_block {aka struct fz_stext_block_s}’ has no member named ‘len’
          text_line < text_block->lines + text_block->len;
                                                      ^~~
pdf_document.cpp:271:12: error: ‘fz_stext_span’ was not declared in this scope
       for (fz_stext_span* text_span = text_line->first_span;
            ^~~~~~~~~~~~~
pdf_document.cpp:271:12: note: suggested alternative: ‘fz_text_span’
       for (fz_stext_span* text_span = text_line->first_span;
            ^~~~~~~~~~~~~
            fz_text_span
pdf_document.cpp:271:27: error: ‘text_span’ was not declared in this scope
       for (fz_stext_span* text_span = text_line->first_span;
                           ^~~~~~~~~
pdf_document.cpp:271:27: note: suggested alternative: ‘fz_text_span’
       for (fz_stext_span* text_span = text_line->first_span;
                           ^~~~~~~~~
                           fz_text_span
pdf_document.cpp:271:50: error: ‘fz_stext_line {aka struct fz_stext_line_s}’ has no member named ‘first_span’; did you mean ‘first_char’?
       for (fz_stext_span* text_span = text_line->first_span;
                                                  ^~~~~~~~~~
                                                  first_char
pdf_document.cpp:293:3: error: ‘fz_drop_stext_sheet’ was not declared in this scope
   fz_drop_stext_sheet(_fz_context, text_sheet);
   ^~~~~~~~~~~~~~~~~~~
pdf_document.cpp:293:3: note: suggested alternative: ‘fz_drop_stext_page’
   fz_drop_stext_sheet(_fz_context, text_sheet);
   ^~~~~~~~~~~~~~~~~~~
   fz_drop_stext_page
make: *** [<builtin>: pdf_document.o] Error 1
```
